# general setting
name: faust
backend: dp # DataParallel
type: SpatialLearningBasisModel #
num_gpu: 1 #
gpu_idx: 1 #
manual_seed: 1234
non-isometric: false
partial: false
save_filter: true
zoomout_refine: true

# path
path:
  resume_state: ~

# datasets
datasets:
  train_dataset:
    name: FaustTrain
    type: PairFaustDataset
    phase: train
    data_root: ../data/FAUST_r
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: False
    return_dist: False
  # test_dataset1:
  #   name: FaustTest
  #   type: PairFaustDataset
  #   phase: test
  #   data_root: ../data/FAUST_r
  #   return_evecs: True
  #   return_faces: True
  #   num_evecs: 200
  #   return_corr: True
  #   return_dist: True
  # test_dataset2:
  #   name: FaustVal
  #   type: PairDataset
  #   data_root: ../data/FAUST_a/
  #   return_evecs: True
  #   return_faces: True
  #   num_evecs: 200
  #   return_corr: True
  #   return_dist: True   
  test_dataset:
    name: Shrec19Val
    type: PairShrec19Dataset
    phase: test
    data_root: ../data/SHREC19_r
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_dist: True
  #setting for train dataset
  batch_size: 1
  num_worker: 8

# 不考虑交叉泛化

networks:
  #1 extracor 
  feature_extractor:
    type: DiffusionNet
    in_channels: 16
    out_channels: 128
    cache_dir: ../data/FAUST_r/diffusion
    input_type: hks
  permutation:
    type: Similarity
    tau: 0.07
  #2 network setting
  basisconv:
    type: EigenBasis_Fliters
    C_inout: 200
    filter_type: heat_delta  #

# training setting 需要修改
train:
  total_epochs: 10 # 15
  optims: 
    feature_extractor:
      type: Adam
      lr: 1.0e-3
    basisconv:
      type: Adam
      lr: 1.0e-3
  schedulers:  # 
    feature_extractor:
      type: CosineAnnealingLR  #
      eta_min: 1.0e-4
      T_max: 15
    basisconv:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 15
  losses:
    rfmnet_loss:
      type: RfmnetLoss
      loss_weight: 1.0
    # contrastive_loss:
    #   type: SelfLoss
    #   loss_weight: 5.0  

# validation setting
val:
  val_freq: 2000 # 4000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 100
  save_checkpoint_freq: 2000
